[ClassVersion("1.0.1.0"), FriendlyName("xADDomainController")]
class MSFT_xADDomainController : OMI_BaseResource
{
    [Key, Description("The FQDN of the domain the Domain Controller will be joining.")] String DomainName;
    [Required, Description("The 'PSCredential' object containing Domain Administrator rights to add the Domain Controller to the domain."), EmbeddedInstance("MSFT_Credential")] String DomainAdministratorCredential;
    [Required, Description("The 'PSCredential' object containing the password to use for DSRM."), EmbeddedInstance("MSFT_Credential")] String SafemodeAdministratorPassword;
    [Write, Description("The path where the database will be stored.")] String DatabasePath;
    [Write, Description("The path where the logs will be stored.")] String LogPath;
    [Write, Description("The path where the Sysvol will be stored.")] String SysvolPath;
    [Write, Description("The name of the site this Domain Controller will be added to.")] String SiteName;
    [Write, Description("The path of the media you want to use install the Domain Controller.")] String InstallationMediaPath;
    [Write, Description("Specifies if the domain controller will be a Global Catalog (GC).")] Boolean IsGlobalCatalog;
    [Read, Description("The state of the Domain Controller.")] String Ensure;
};
