ConvertFrom-StringData @'
    ResolveDomainName                           = Resolving the domain name '{0}'. (ADDC0001)
    DomainPresent                               = The domain '{0}' is present. Looking for domain controllers. (ADDC0002)
    IsDomainController                          = The current node '{0}' is a domain controller for the domain '{1}'. (ADDC0003)
    NotDomainController                         = The current node '{0}' is not a domain controller. (ADDC0004)
    MissingDomain                               = Current node could not find the domain '{0}'. (ADDC0005)
    Promoting                                   = Promoting the current node to be a domain controller for the domain '{1}'. (ADDC0006)
    Promoted                                    = The current node '{0}' has been promoted to a domain controller for the domain '{1}'. (ADDC0007)
    AddGlobalCatalog                            = Adding Global Catalog to the domain controller. (ADDC0008)
    RemoveGlobalCatalog                         = Removing Global Catalog from the domain controller. (ADDC0009)
    MovingDomainController                      = Moving Domain Controller from site '{0}' to site '{1}'. (ADDC0010)
    FailedToFindSite                            = The site '{0}' could not be found in the domain '{1}'. (ADDC0011)
    TestingConfiguration                        = Determine the state of the domain controller on the current node '{0}' in the domain '{1}'. (ADDC0012)
    WrongSite                                   = The domain controller is in the site '{0}', but expected it to be in the site '{1}'. (ADDC0013)
    ExpectedGlobalCatalogEnabled                = The domain controller does not contain a Global Catalog, but it was expected to have a Global Catalog. (ADDC0014)
    ExpectedGlobalCatalogDisabled               = The domain controller have a Global Catalog, but it was expected to not have a Global Catalog. (ADDC0015)
    AllowedSyncAccountsMismatch                 = There is a mismatch in AllowPasswordReplicationAccountName list. Got {0}, expected was {1}. (ADDC0016)
    DenySyncAccountsMismatch                    = There is a mismatch in DenyPasswordReplicationAccountName list. Got {0}, expected was {1}. (ADDC0017)
    RODCMissingSite                             = You have specified 'ReadOnlyReplica', but did not provide a site name. (ADDC0018)
    CannotConvertToRODC                         = Cannot convert a existing domain controller to a Read-Only Domain Controller (RODC). (ADDC0019)
    NotOwnerOfFlexibleSingleMasterOperationRole = The domain controller was expected to be the owner of the Flexible Single Master Operation (FSMO) role '{0}', but it is not. (ADDC0020)
    MovingFlexibleSingleMasterOperationRole     = The Flexible Single Master Operation (FSMO) role '{0}' is being moved from domain controller '{1}' to this domain controller. (ADDC0021)
'@
