ConvertFrom-StringData @'
    ResolveDomainName                           = Resolving the domain name '{0}'. (ADRODCA0001)
    DomainPresent                               = The domain '{0}' is present. Looking for read only domain controller account. (ADRODCA0002)
    NotReadOnlyDomainControllerAccount          = The read only domain controller account '{0}' does not exist in the domain '{1}'. (ADRODCA0003)
    IsReadOnlyDomainControllerAccount           = The read only domain controller account '{0}' does exist in the domain '{1}'. (ADRODCA0004)
    MissingDomain                               = Current node could not find the domain '{0}'. (ADRODCA0005)
    Adding                                      = Adding read only domain controller account '{0}' to the domain '{1}'. (ADRODCA0006)
    Added                                       = Added read only domain controller account '{0}' to the domain '{1}'. (ADRODCA007)
    AddGlobalCatalog                            = Adding Global Catalog to the read only domain controller account. (ADRODCA008)
    RemoveGlobalCatalog                         = Removing Global Catalog from the read only domain controller account. (ADRODCA009)
    MovingDomainController                      = Moving Read Only Domain Controller account from site '{0}' to site '{1}'. (ADRODCA0010)
    FailedToFindSite                            = The site '{0}' could not be found in the domain '{1}'. (ADRODCA0011)
    TestingConfiguration                        = Determine the state of the read only domain controller account '{0}' in the domain '{1}'. (ADRODCA0012)
    WrongSite                                   = The read only domain controller account is in the site '{0}', but expected it to be in the site '{1}'. (ADRODCA0013)
    ExpectedGlobalCatalogEnabled                = The read only domain controller account does not have a Global Catalog, but it was expected to have a Global Catalog. (ADRODCA0014)
    ExpectedGlobalCatalogDisabled               = The read only domain controller account has a Global Catalog, but it was expected to not have a Global Catalog. (ADRODCA0015)
    AllowedSyncAccountsMismatch                 = There is a mismatch in AllowPasswordReplicationAccountName list. Got {0}, expected was {1}. (ADRODCA0016)
    DenySyncAccountsMismatch                    = There is a mismatch in DenyPasswordReplicationAccountName list. Got {0}, expected was {1}. (ADRODCA0017)
    DelegatedAdministratorAccountNameMismatch   = There is a mismatch in DelegatedAdministratorAccountName. Got {0}, expected was {1}. (ADRODCA0018)
    UpdatingDelegatedAdministratorAccountName   = Updating the DelegatedAdministratorAccountName from the name {0} to the name {1}. (ADRODCA0019)
'@
