[ClassVersion("1.0.0.0"), FriendlyName("xWaitForADDomain")]
class MSFT_xWaitForADDomain : OMI_BaseResource
{
    [Key] String DomainName;
  [Required, EmbeddedInstance("MSFT_Credential")] String DomainUserCredential;
    [Write] Uint64 RetryIntervalSec;
    [Write] Uint32 RetryCount;
};

