[ClassVersion("1.0.0"), FriendlyName("ADFineGrainedPasswordPolicy")]
class MSFT_ADFineGrainedPasswordPolicy : OMI_BaseResource
{
    [Key, Description("Name of the fine grained password policy.")] String Name;
    [Write, Description("The display name of the policy object.")] String DisplayName;
    [Write, Description("Specifies whether the fine grained password policy should be present or absent. Default value is 'Present'."), ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] String Ensure;
    [Write, Description("Whether password complexity is enabled for the fine grained password policy.")] Boolean ComplexityEnabled;
    [Write, Description("Length of time that an account is locked after the number of failed login attempts (timespan minutes).")] String LockoutDuration;
    [Write, Description("Maximum time between two unsuccessful login attempts before the counter is reset to 0 (timespan minutes).")] String LockoutObservationWindow;
    [Write, Description("Number of unsuccessful login attempts that are permitted before an account is locked out.")] UInt32 LockoutThreshold;
    [Write, Description("Minimum length of time that you can have the same password (timespan days).")] String MinPasswordAge;
    [Write, Description("Maximum length of time that you can have the same password (timespan days).")] String MaxPasswordAge;
    [Write, Description("Minimum number of characters that a password must contain.")] UInt32 MinPasswordLength;
    [Write, Description("Number of previous passwords to remember.")] UInt32 PasswordHistoryCount;
    [Write, Description("Whether the directory must store passwords using reversible encryption.")] Boolean ReversibleEncryptionEnabled;
    [Write, Description("Whether to protect the object from accidental deletion.")] Boolean ProtectedFromAccidentalDeletion;
    [Write, Description("The rank order for the policy.")] UInt32 Precedence;
    [Write, Description("Active Directory domain controller to enact the change upon.")] String DomainController;
    [Write, Description("Credentials used to access the domain."), EmbeddedInstance("MSFT_Credential")] String Credential;
};

