[ClassVersion("1.0.0.0"), FriendlyName("xADRecycleBin")]
class MSFT_xADRecycleBin : OMI_BaseResource
{
    [Key, Description("The FQDN of the forest in which to change the Recycle Bin feature.")] String ForestFQDN;
    [Required, Description("The user account credentials to use to perform this task."), EmbeddedInstance("MSFT_Credential")] String EnterpriseAdministratorCredential;
    [Read, Description("The state of the Recycle Bin feature.")] String RecycleBinEnabled;
    [Read, Description("The functional level of the forest.")] String ForestMode;
};
