[ClassVersion("1.0.1.0"), FriendlyName("xADManagedServiceAccount")]
class MSFT_xADManagedServiceAccount : OMI_BaseResource
{
    [Key, Description("Name of the Active Directory managed service account")] String ServiceAccountName;
    [Write, Description("Type of managed service account"), ValueMap{"Group","Single"}, Values{"Group","Single"}] String AccountType;
    [Write, Description("Location of the group within Active Directory expressed as a Distinguished Name")] String Path;
    [Write, Description("Should this resource be present or absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Description of the Active Directory managed service account")] String Description;
    [Write, Description("Display name of the Active Directory managed service account")] String DisplayName;
    [Write, Description("Active Directory domain controller to enact the change upon")] String DomainController;
    [Write, Description("Credentials used to enact the change upon"), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Indicates whether an account is enabled. This parameter sets the Enabled property for an account object")] Boolean Enabled;
    [Write, Description("Specifies the membership policy for systems that can use a group-managed service account. For a service to run under a group managed service account, the system must be in the membership policy of the account")] String Members[];
    [Write, Description("Active Directory attribute used to perform membership operations"), ValueMap{"SamAccountName","DistinguishedName","ObjectGUID","SID"}, Values{"SamAccountName","DistinguishedName","ObjectGUID","SID"}] String MembershipAttribute;
    [Read, Description("Specifies the Distinguished Name of the Service Account")] String DistinguishedName;
};
