[ClassVersion("1.0.1.0"), FriendlyName("xADManagedServiceAccount")]
class MSFT_xADManagedServiceAccount : OMI_BaseResource
{
    [Key, Description("Name of the Active Directory managed service account")] String Name;
    [Write, Description("Location of the group within Active Directory expressed as a Distinguished Name")] String Path;
    [Write, Description("Should this resource be present or absent"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Description of the Active Directory managed service account")] String Description;
    [Write, Description("Display name of the Active Directory managed service account")] String DisplayName;
    [Write, Description("Credentials used to enact the change upon"), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Active Directory domain controller to enact the change upon")] String DomainController;
};
