[ClassVersion("1.0.1.0"), FriendlyName("xADManagedServiceAccount")]
class MSFT_xADManagedServiceAccount : OMI_BaseResource
{
    [Key, Description("Specifies the Security Account Manager (SAM) account name of the managed service account (ldapDisplayName 'sAMAccountName')")] String ServiceAccountName;
    [Write, Description("The type of managed service account. Single with create a Single Managed Service Account (sMSA) and Group will create a Group Managed Service Account (gMSA)"), ValueMap{"Group","Single"}, Values{"Group","Single"}] String AccountType;
    [Write, Description("Specifies the X.500 path of the Organizational Unit (OU) or container where the new object is created")] String Path;
    [Write, Description("Specifies whether the user account is created or deleted"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Specifies a description of the object (ldapDisplayName 'description')")] String Description;
    [Write, Description("Specifies the display name of the object (ldapDisplayName 'displayName')")] String DisplayName;
    [Write, Description("Specifies the Active Directory Domain Controller instance to use to perform the task")] String DomainController;
    [Write, Description("Specifies the user account credentials to use to perform this task"), EmbeddedInstance("MSFT_Credential")] String Credential;
    [Write, Description("Specifies the members of the object (ldapDisplayName 'PrincipalsAllowedToRetrieveManagedPassword'). Only used when 'Group' is selected for 'AccountType'")] String Members[];
    [Write, Description("Active Directory attribute used to perform membership operations for Group Managed Service Accounts (gMSAs)"), ValueMap{"SamAccountName","DistinguishedName","ObjectGUID","SID"}, Values{"SamAccountName","DistinguishedName","ObjectGUID","SID"}] String MembershipAttribute;
    [Write, Description("Specifies whether or not to remove the service account and recreate it when going from single MSA to group MSA and vice-versa")] Boolean AccountTypeForce;
    [Read, Description("Specifies the Distinguished Name of the Service Account")] String DistinguishedName;
    [Read, Description("Specifies whether the user account is enabled or disabled")] Boolean Enabled;
};
