# culture="en-US"
ConvertFrom-StringData @'
    RetrievingGroupMembers               = Retrieving group membership based on '{0}' property. (ADG0001)
    GroupMembershipNotDesiredState       = Group membership is NOT in the desired state. (ADG0002)
    AddingGroupMembers                   = Adding '{0}' member(s) to AD group '{1}'. (ADG0003)
    RemovingGroupMembers                 = Removing '{0}' member(s) from AD group '{1}'. (ADG0004)
    AddingGroup                          = Creating AD Group '{0}'. (ADG0005)
    RemovingGroup                        = Removing AD Group '{0}'. (ADG0007)
    MovingGroup                          = Moving AD Group '{0}' to '{1}'. (ADG0008)
    RestoringGroup                       = Attempting to restore the group {0} from recycle bin. (ADG0009)
    UpdatingResourceProperty             = Updating AD Group '{0}' property '{1}' to '{2}'. (ADG0012)
    RetrievingGroupMembersError          = Error retrieving membership for AD Group '{0}'. (ADG0014)
    ResourceExistsButShouldNotMessage    = AD Group '{0}' exists but should not. (ADG0015)
    ResourceDoesNotExistButShouldMessage = AD Group '{0}' does not exist but should. (ADG0016)
    AddingGroupError                     = Error adding AD Group '{0}'. (ADG0017)
    RemovingGroupError                   = Error removing AD Group '{0}'. (ADG0018)
    MovingGroupError                     = Error moving AD Group '{0}' from '{1}' to '{2}'. (ADG0019)
    SettingGroupError                    = Error setting AD Group '{0}'. (ADG0020)
    RetrievingGroup                      = Retrieving AD Group '{0}'. (ADG0021)
    RetrievingGroupError                 = Error Retrieving AD Group '{0}'. (ADG0022)
    GroupIsPresent                       = The AD Group '{0}' is present. (ADG0023)
    GroupIsAbsent                        = The AD Group '{0}' is absent. (ADG0024)
    ResourceInDesiredStateMessage        = AD Group '{0}' is in the desired state. (ADG0025)
'@
