[ClassVersion("1.0.1.0"), FriendlyName("xADUser")] 
class MSFT_xADUser : OMI_BaseResource
{
    [Key] String DomainName;
    [Key] String UserName;
    [Write, EmbeddedInstance("MSFT_Credential")] String Password;
    [Write, ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
    [Write] String CommonName;
    [Write] String UserPrincipalName;
    [Write] String DisplayName;
    [Write] String Path;
    [Write] String GivenName;
    [Write] String Initials;
    [Write] String Surname;
    [Write] String Description;
    [Write] String StreetAddress;
    [Write] String POBox;
    [Write] String City;
    [Write] String State;
    [Write] String PostalCode;
    [Write] String Country;
    [Write] String Department;
    [Write] String Division;
    [Write] String Company;
    [Write] String Office;
    [Write] String JobTitle;
    [Write] String EmailAddress;
    [Write] String EmployeeID;
    [Write] String EmployeeNumber;
    [Write] String HomeDirectory;
    [Write] String HomeDrive;
    [Write] String HomePage;
    [Write] String ProfilePath;
    [Write] String LogonScript;
    [Write] String Notes;
    [Write] String OfficePhone;
    [Write] String MobilePhone;
    [Write] String Fax;
    [Write] String HomePhone;
    [Write] String Pager;
    [Write] String IPPhone;
    [Write] String Manager;
    [Write] Boolean Enabled;
    [Write] Boolean CannotChangePassword;
    [Write] Boolean PasswordNeverExpires;
    [Write] String DomainController;
    [Write, EmbeddedInstance("MSFT_Credential")] String DomainAdministratorCredential;
    [Read, Description("")] String DistinguishedName;
};
