[ClassVersion("1.0.1.0"), FriendlyName("xADUser")] 
class MSFT_xADUser : OMI_BaseResource
{
    [Key] string DomainName;
    [Key] string UserName;
    [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
    [write,EmbeddedInstance("MSFT_Credential")] string Password;
    [required,EmbeddedInstance("MSFT_Credential")] string DomainAdministratorCredential;
};
