# culture="en-US"
ConvertFrom-StringData @'
    QueryingFineGrainedPasswordPolicy             = Querying policy '{0}'. (ADFGPP0001)
    CreatingFineGrainedPasswordPolicy             = Creating policy '{0}'. (ADFGPP0002)
    RemovingFineGrainedPasswordPolicy             = Removing policy '{0}'. (ADFGPP0003)
    SettingPasswordPolicyValue                    = Setting policy '{0}' property to '{1}'. (ADFGPP0004)
    ResourceInDesiredState                        = Policy '{0}' is in the desired state. (ADFGPP0005)
    ResourceNotInDesiredState                     = Policy '{0}' is not in the desired state. (ADFGPP0006)
    ResourceConfigurationError                    = Error setting policy '{0}'. (ADFGPP0007)
    ResourceRemovalError                          = Error removing policy '{0}'. (ADFGPP0008)
    RetrieveFineGrainedPasswordPolicyError        = Error retrieving policy '{0}'. (ADFGPP0009)
    RetrieveFineGrainedPasswordPolicySubjectError = Error retrieving policy subject '{0}'. (ADFGPP0010)
    ResourceExistsButShouldNotMessage             = Policy '{0}' exists but should not. (ADFGPP0011)
    ResourceDoesNotExistButShouldMessage          = Policy '{0}' does not exist but should. (ADFGPP0012)
    ProtectedFromAccidentalDeletionRemove         = Removing the protection for accidental deletion for policy '{0}'. (ADFGPP0013)
    AddingPasswordPolicySubjects                  = Adding new subjects to policy '{0}', count '{1}'. (ADFGPP0014)
    RemovingPasswordPolicySubjects                = Removing existing subjects from policy '{0}', count '{1}'. (ADFGPP0015)
    AddingPasswordPolicySubjectsError             = Error adding subjects to policy '{0}'. (ADFGPP0016)
    RemovingPasswordPolicySubjectsError           = Error removing subjects from policy '{0}'. (ADFGPP0017)
    PasswordPolicyNotFound                        = Policy '{0}' was not found. (ADFGPP0018)
'@
