[ClassVersion("1.0.0.0"), FriendlyName("xADServiceAccountOnComputer")]
class MSFT_xADServiceAccountOnComputer : OMI_BaseResource
{
    [Write, Description("An enumerated value that describes if the Active Directory service account is installed on the machine.\nPresent {default}  \nAbsent   \n"), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key, Description("Specifies an Active Directory service account object by account name.")] String Identity;
};