[ClassVersion("1.0.0.0"), FriendlyName("xADReplicationSubnet")]
class MSFT_xADReplicationSubnet : OMI_BaseResource
{
    [Write, Description("Specifies if the AD replication subnet should be added or remove. Default value is 'Present'."), ValueMap{"Present", "Absent"}, Values{"Present", "Absent"}] string Ensure;
    [Key, Description("The name of the AD replication subnet, e.g. 10.0.0.0/24.")] string Name;
    [Required, Description("The name of the assigned AD replication site, e.g. Default-First-Site-Name.")] string Site;
    [Write, Description("The location for the AD replication site. Default value is empty.")] string Location;
};
